# Generated by Django 6.1 on 2026-09-02 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32camera',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='esp32camera',
            name='storage_space',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='videocapture',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='backend.esp32camera'),
        ),
    ]
